services:
  app:
    build:
      context: .
    image: google-drive-documents-downloader:latest
    ports:
      - "8080:8080"
    env_file:
      - ./google-drive.env
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: "/run/secrets/google-service-account.json"
      DOWNLOAD_LOG_DB_PATH: "/data/download-log"
    volumes:
      - "./secrets/service-account.json:/run/secrets/google-service-account.json:ro"
      - "download-data:/data"

volumes:
  download-data:
